{{- if .Values.secrets.aws.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.aws.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "mds.labels" . | nindent 4 }}
type: Opaque
stringData:
  region: {{ required "AWS region is required" (index .Values.secrets.aws.data "region") | quote }}
  access-key-id: {{ required "AWS access key ID is required" (index .Values.secrets.aws.data "access-key-id") | quote }}
  secret-access-key: {{ required "AWS secret access key is required" (index .Values.secrets.aws.data "secret-access-key") | quote }}
  boreal-connection-hub-vpc-endpoint-service-name: {{ required "AWS Boreal connection hub VPC endpoint service name is required" (index .Values.secrets.aws.data "boreal-connection-hub-vpc-endpoint-service-name") | quote }}
{{- end }}