---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.borealWebhook.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "mds.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret: {{ required "Boreal webhook secret is required" (default .Values.secrets.borealWebhook.secret (index .Values.secrets.borealWebhook.data "secret")) | quote }}