---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.defaultMoosePod.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "mds.labels" . | nindent 4 }}
type: Opaque
stringData:
  cpu: {{ required "Default Moose pod CPU is required" (index .Values.secrets.defaultMoosePod.data "cpu") | quote }}
  memory: {{ required "Default Moose pod memory is required" (index .Values.secrets.defaultMoosePod.data "memory") | quote }}