{{- if .Values.secrets.redis.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.redis.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "mds.labels" . | nindent 4 }}
type: Opaque
stringData:
  connection-string: {{ required "Redis connection string is required" (index .Values.secrets.redis.data "connection-string") | quote }}
  mds-cluster-prefix: {{ required "Redis MDS cluster prefix is required" (index .Values.secrets.redis.data "mds-cluster-prefix") | quote }}
  mds-request-channel: {{ required "Redis MDS request channel is required" (index .Values.secrets.redis.data "mds-request-channel") | quote }}
  region: {{ required "Redis region is required" (index .Values.secrets.redis.data "region") | quote }}
  db-name: {{ required "Redis DB name is required" (index .Values.secrets.redis.data "db-name") | quote }}
  api-key: {{ required "Redis API key is required" (index .Values.secrets.redis.data "api-key") | quote }}
  secret-key: {{ required "Redis secret key is required" (index .Values.secrets.redis.data "secret-key") | quote }}
  subscription-id: {{ required "Redis subscription ID is required" (index .Values.secrets.redis.data "subscription-id") | quote }}
{{- end }}