{{- if .Values.secrets.redpanda.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.redpanda.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "mds.labels" . | nindent 4 }}
type: Opaque
stringData:
  auth-url: {{ required "Redpanda auth URL is required" (index .Values.secrets.redpanda.data "auth-url") | quote }}
  client-id: {{ required "Redpanda client ID is required" (index .Values.secrets.redpanda.data "client-id") | quote }}
  client-secret: {{ required "Redpanda client secret is required" (index .Values.secrets.redpanda.data "client-secret") | quote }}
  cluster-api-url: {{ required "Redpanda cluster API URL is required" (index .Values.secrets.redpanda.data "cluster-api-url") | quote }}