# Chart Testing configuration
remote: origin
target-branch: main
chart-dirs:
  - charts
chart-repos: []
helm-extra-args: --timeout 600s
check-version-increment: true
validate-maintainers: false
validate-chart-schema: true
validate-yaml: true
exclude-deprecated: true
excluded-charts: [] 