{{- if .Values.secrets.clickhouse.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.clickhouse.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "mds.labels" . | nindent 4 }}
type: Opaque
stringData:
  cloud-provider: {{ required "Clickhouse cloud provider is required" (index .Values.secrets.clickhouse.data "cloud-provider") | quote }}
  cloud-region: {{ required "Clickhouse cloud region is required" (index .Values.secrets.clickhouse.data "cloud-region") | quote }}
  org-id: {{ required "Clickhouse org ID is required" (index .Values.secrets.clickhouse.data "org-id") | quote }}
  token-key: {{ required "Clickhouse token key is required" (index .Values.secrets.clickhouse.data "token-key") | quote }}
  token-secret: {{ required "Clickhouse token secret is required" (index .Values.secrets.clickhouse.data "token-secret") | quote }}
{{- end }}